config/routes.rb
Rails.application.routes.draw do
  devise_for :students, controllers: { registrations: 'students/registrations' }
  devise_for :teachers, controllers: { registrations: 'teachers/registrations' }

  get 'students', to: 'students#index', as: 'students'
  get 'students/:id', to: 'students#show', as: 'student'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

app/views/home/index.html.erb
<!-- app/views/home/index.html.erb -->
<div class="container mt-4">
  <h1>Welcome to School Management System</h1>
  <hr>

  <% if student_signed_in? %>
    <div class="mt-4">
      <p><strong>Hello</strong> <%= current_student.name %></p>
      <p><strong>Contact:</strong> <%= current_student.contact %></p>
      <p><strong>Grade:</strong> <%= current_student.grade %></p>
      <p><strong>Email:</strong> <%= current_student.email %></p>

      <%= button_to "Logout", destroy_student_session_path, method: :delete, class: "btn btn-danger mt-2" %>
    </div>
  <% elsif teacher_signed_in? %>
    <div class="mt-4">
      <p><strong>Hello</strong> <%= current_teacher.name %></p>
      <p><strong>Contact:</strong> <%= current_teacher.contact %></p>
      <p><strong>Department:</strong> <%= current_teacher.department %></p>
      <p><strong>Email:</strong> <%= current_teacher.email %></p>
      <%= button_to "Logout", destroy_teacher_session_path, method: :delete, class: "btn btn-danger mt-2" %>

      <!-- Displaying list of students with links -->
      <div class="container mt-4">
        <h1>Students List</h1>

        <% @students.each do |student| %>
          <div class="student">
            <p><strong>Name:</strong> <%= link_to student.name, student_path(student) %></p>
            
            <hr>
          </div>
        <% end %>
      </div>

      
    </div>
  <% else %>
    <div class="mt-4">
      <%= link_to "Login as Student", new_student_session_path, class: "btn btn-primary mr-2" %>
      <%= link_to "Login as Teacher", new_teacher_session_path, class: "btn btn-primary mr-2" %>
<hr>
    <h6 class="text-danger">Only for testing purpose / for admin / these links can be removed for production</h6>
      <%= link_to "Signup as Student", new_student_registration_path, class: "btn btn-success mr-2" %>
      <%= link_to "Signup as Teacher", new_teacher_registration_path, class: "btn btn-success" %>
    </div>
  <% end %>
</div>